"""
Script to plot retention metrics by fishtype, time window, and kill fish.

Usage:
    python plot_game_retention_by_fishtype_time.py

The script will:
    - Load the parquet data generated by etl_game_retention_by_fishtype_time.py
    - Create plots with kill_fish as x-axis, time_window as grouped bars,
      retention ratios on left y-axis (bar plot), and num_users on right y-axis (line plot)
    - Generate separate plots for each fish_type level
"""

import os
from typing import List, Optional

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from bituslabs_ds.config import LOCAL_ROOT, setup_logging


def load_data(file_path: str) -> pd.DataFrame:
    """
    Load parquet data file.

    Args:
        file_path: Path to parquet file

    Returns:
        DataFrame with loaded data

    Raises:
        FileNotFoundError: If file doesn't exist
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")

    df = pd.read_parquet(file_path)
    print(f"Loaded {len(df)} rows from parquet file: {file_path}")
    print(f"Columns: {list(df.columns)}")
    return df


def create_grouped_bar_with_line_plot(
    df: pd.DataFrame,
    x_col: str,
    group_col: str,
    bar_cols: List[str],
    line_col: str,
    facet_col: Optional[str] = None,
    facet_value: Optional[str] = None,
    output_dir: Optional[str] = None,
    fig_size: tuple = (14, 8),
    title_suffix: str = "",
):
    """
    Create a grouped bar plot (for bar_cols) with a line plot (for line_col) on dual y-axes.

    Args:
        df: DataFrame with data
        x_col: Column name for x-axis tick labels
        group_col: Column name to group by (creates multiple bars per x-tick)
        bar_cols: List of column names to plot as bars (left y-axis)
        line_col: Column name to plot as line (right y-axis)
        facet_col: Column name to facet by (if None, creates single plot)
        facet_value: Value of facet_col to filter for this plot (if facet_col is not None)
        output_dir: Directory to save plot (None = just display)
        fig_size: Figure size tuple
        title_suffix: Additional text to append to title
    """
    # Filter by facet value if specified
    if facet_col is not None and facet_value is not None:
        df_plot = df[df[facet_col] == facet_value].copy()
        title_prefix = f"{facet_col}={facet_value}"
    else:
        df_plot = df.copy()
        title_prefix = ""

    if len(df_plot) == 0:
        print(f"Warning: No data for {title_prefix}, skipping plot")
        return

    # Get unique values for x-axis and group column
    # Sort to ensure consistent ordering
    x_values = sorted(df_plot[x_col].unique(), key=str)
    group_values = sorted(df_plot[group_col].unique(), key=str)

    # Set up color palette for group_col
    colors_bar = sns.color_palette("Set2", len(group_values))
    color_map_bar = dict(zip(group_values, colors_bar))

    # Create figure with dual y-axes
    fig, ax1 = plt.subplots(figsize=fig_size)

    # Prepare data for grouped bar plot
    # Structure: For each x_value (kill_fish), we have bars grouped by group_col (time_window)
    # If multiple bar_cols, they are shown as separate bars within each group
    n_x_groups = len(x_values)
    n_group_values = len(group_values)
    n_bar_cols = len(bar_cols)

    # Total number of bars per x position: n_group_values groups, each with n_bar_cols bars
    total_bars_per_x = n_group_values * n_bar_cols
    bar_width = 0.8 / total_bars_per_x if total_bars_per_x > 0 else 0.8
    x_positions = np.arange(n_x_groups)

    # Use different hatches for different bar columns (only if multiple bar_cols)
    hatches = ["", "/", "\\", "x", ".", "o", "-", "|"]

    # Plot bars: for each group_val, then for each bar_col
    for group_idx, group_val in enumerate(group_values):
        for bar_idx, bar_col in enumerate(bar_cols):
            # Calculate position: group bars by group_val first, then by bar_col
            # Position within the 0.8 width span
            if total_bars_per_x > 1:
                bar_position_in_group = group_idx * n_bar_cols + bar_idx
                offset = (bar_position_in_group - (total_bars_per_x - 1) / 2) * bar_width
            else:
                offset = 0
            x_bar_positions = x_positions + offset

            # Get values for this group and column
            values = []
            for x_val in x_values:
                subset = df_plot[(df_plot[x_col] == x_val) & (df_plot[group_col] == group_val)]
                if len(subset) > 0:
                    values.append(subset[bar_col].iloc[0])
                else:
                    values.append(0)

            # Plot bars with appropriate styling
            # Use hatches only if multiple bar_cols, otherwise simple bars
            hatch = hatches[bar_idx % len(hatches)] if n_bar_cols > 1 else ""
            label = f"{group_val} - {bar_col}" if len(bar_cols) > 1 else str(group_val)
            color = color_map_bar[group_val]

            ax1.bar(
                x_bar_positions,
                values,
                width=bar_width,
                label=label,
                color=color,
                alpha=0.8,
                edgecolor="black",
                linewidth=0.5,
                hatch=hatch if hatch else None,
            )

    # Configure left y-axis (for bars)
    ax1.set_xlabel(x_col, fontsize=12)
    # Use the first bar_col for ylabel (or all if multiple)
    ylabel_text = bar_cols[0] if len(bar_cols) == 1 else " / ".join(bar_cols)
    ax1.set_ylabel(ylabel_text, fontsize=12, color="b")
    ax1.set_xticks(x_positions)
    ax1.set_xticklabels(x_values, rotation=45, ha="right")
    ax1.tick_params(axis="y", labelcolor="b")
    ax1.grid(axis="y", linestyle="--", alpha=0.3)

    # Create right y-axis for line plot
    ax2 = ax1.twinx()

    # Plot line for each group value
    markers = ["o", "s", "^", "v", "D", "p", "*", "h"]
    for group_idx, group_val in enumerate(group_values):
        # Get values for this group
        values = []
        for x_val in x_values:
            subset = df_plot[(df_plot[x_col] == x_val) & (df_plot[group_col] == group_val)]
            if len(subset) > 0:
                values.append(subset[line_col].iloc[0])
            else:
                values.append(0)

        # Plot line
        marker = markers[group_idx % len(markers)]
        ax2.plot(
            x_positions,
            values,
            marker=marker,
            linestyle="--",
            linewidth=2,
            markersize=8,
            label=f"{group_val} - {line_col}",
            color=color_map_bar[group_val],
        )

    # Configure right y-axis (for line)
    ax2.set_ylabel(line_col, fontsize=12, color="r")
    ax2.tick_params(axis="y", labelcolor="r")

    # Combine legends
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    all_lines = lines1 + lines2
    all_labels = labels1 + labels2

    # Create title
    metric_name = bar_cols[0] if len(bar_cols) == 1 else "Retention Metrics"
    title = f"{metric_name} by {x_col} and {group_col}"
    if title_prefix:
        title = f"{title_prefix}: {title}"
    if title_suffix:
        title = f"{title} {title_suffix}"
    ax1.set_title(title, fontsize=14, fontweight="bold", pad=20)

    # Place legend
    ax1.legend(all_lines, all_labels, loc="best", fontsize=9, framealpha=0.5)

    plt.tight_layout()

    # Save or display
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
        safe_x_col = x_col.replace(" ", "_").replace("/", "_")
        safe_group_col = group_col.replace(" ", "_").replace("/", "_")

        # Create filename components
        filename_parts = ["plot"]
        if facet_col and facet_value:
            safe_facet = str(facet_value).replace(" ", "_").replace("/", "_")
            filename_parts.append(safe_facet)
        if len(bar_cols) == 1:
            # Include metric name in filename when single metric
            safe_bar_col = bar_cols[0].replace(" ", "_").replace("/", "_")
            filename_parts.append(safe_bar_col)
        filename_parts.extend([safe_x_col, "by", safe_group_col])

        output_path = os.path.join(output_dir, "_".join(filename_parts) + ".png")
        plt.savefig(output_path, dpi=300, bbox_inches="tight")
        print(f"  Saved: {output_path}")
    else:
        plt.show()

    plt.close()


def main():
    """Main function to run the plotting script."""
    # Configuration
    input_file = f"{LOCAL_ROOT}/jobs/output_fish_hunter/retention_by_time_fishtype.parquet"
    output_dir = f"{LOCAL_ROOT}/jobs/output_fish_hunter/retention_by_time_fishtype_plots"

    # Define columns
    x_col = "time_window"
    group_col = "kill_fish"
    facet_col = "fish_type"
    line_col = "num_users"

    # Detect retention ratio columns (ending with _retention_ratio)
    try:
        df = load_data(input_file)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("Please run etl_game_retention_by_fishtype_time.py first to generate the data.")
        return

    # Find all columns ending with _retention_ratio
    retention_metrics = [col for col in df.columns if col.endswith("_retention_ratio")]
    if not retention_metrics:
        print("Error: No columns ending with '_retention_ratio' found in the data.")
        print(f"Available columns: {list(df.columns)}")
        return

    print(f"\nDetected retention ratio columns: {retention_metrics}")
    print(f"Line column: {line_col}")
    print(f"X-axis column: {x_col}")
    print(f"Group column: {group_col}")
    print(f"Facet column: {facet_col}\n")

    # Get unique facet values
    if facet_col in df.columns:
        facet_values = sorted(df[facet_col].unique(), key=str)
        print(f"Creating plots for {len(facet_values)} levels of {facet_col}: {facet_values}\n")
    else:
        print(f"Warning: Facet column '{facet_col}' not found in data. Creating single plot.")
        facet_values = [None]

    # Create separate plots for each retention metric
    total_plots = 0
    for retention_metric in retention_metrics:
        print(f"\n=== Creating plots for {retention_metric} ===")
        bar_cols = [retention_metric]  # Single metric per plot

        # Create plots for each facet value (fish_type)
        for facet_value in facet_values:
            if facet_value is not None:
                print(f"  Creating plot for {facet_col}={facet_value}...")
            else:
                print("  Creating plot...")

            create_grouped_bar_with_line_plot(
                df=df,
                x_col=x_col,
                group_col=group_col,
                bar_cols=bar_cols,
                line_col=line_col,
                facet_col=facet_col if facet_value is not None else None,
                facet_value=facet_value,
                output_dir=output_dir,
                fig_size=(14, 8),
            )
            total_plots += 1

    print(f"\n=== All plots completed! ===")
    print(f"Total plots created: {total_plots}")
    print(f"Output directory: {output_dir}")


if __name__ == "__main__":
    setup_logging(f"{LOCAL_ROOT}/jobs/log", log_filename=os.path.splitext(os.path.basename(__file__))[0] + ".log")
    main()
