name: aws-example
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=11
  - numpy=1.26.0
  - pandas=2.1.0
  - scikit-learn=1.5.0
  - pip
  - pip:
      - sagemaker==2.244.2
      - boto3==1.38.22
      - pyspark==3.5.5
      - matplotlib==3.10.0
