
WITH binned AS (
    SELECT
        t.user_id,
        t.ai_group,
        t.math_table_id,
        t.session_start_date,
        t.session_group,
        t.session_start_ts,
        t.min_created_at,
        t.max_created_at,
        t.activity_date,
        t.spin_id,
        t.fg_rounds,
        t.bet_amount,
        t.delta_bet_amount,
        t.payout,
        t.delta_payout,
        t.balance_after_bet,
        t.delta_t_seconds,
        t.delta_t_seconds_nogap,
        t.profit,
        t.deposit,
        t.withdraw,
        t.streak,
        t.win_streak,
        t.lose_streak,
        t.session_bet_index,
        FLOOR((t.session_bet_index - 1) / 100) AS agg_group
    FROM enriched_ai AS t
),

stats_base AS (
    SELECT
        user_id, ai_group, math_table_id, session_start_date, session_group, agg_group,
        MIN(activity_date) AS activity_date,
        MIN(min_created_at) AS min_created_at,
        MAX(max_created_at) AS max_created_at,
        COUNT(user_id) AS bet_rounds,
        SUM(fg_rounds) AS fg_rounds,

        CAST(AVG(delta_t_seconds) AS BIGINT) AS delta_t_seconds_avg,
        percentile(delta_t_seconds, 0.25) AS delta_t_seconds_p25,
        percentile(delta_t_seconds, 0.50) AS delta_t_seconds_median,
        percentile(delta_t_seconds, 0.75) AS delta_t_seconds_p75,
        STDDEV(delta_t_seconds) AS delta_t_seconds_std,
        MIN(delta_t_seconds) AS delta_t_seconds_min,
        MAX(delta_t_seconds) AS delta_t_seconds_max,

        CAST(AVG(delta_t_seconds_nogap) AS BIGINT) AS delta_t_seconds_nogap_avg,
        percentile(delta_t_seconds_nogap, 0.25) AS delta_t_seconds_nogap_p25,
        percentile(delta_t_seconds_nogap, 0.50) AS delta_t_seconds_nogap_median,
        percentile(delta_t_seconds_nogap, 0.75) AS delta_t_seconds_nogap_p75,
        STDDEV(delta_t_seconds_nogap) AS delta_t_seconds_nogap_std,
        MIN(delta_t_seconds_nogap) AS delta_t_seconds_nogap_min,
        MAX(delta_t_seconds_nogap) AS delta_t_seconds_nogap_max,

        AVG(bet_amount) AS bet_amount_avg,
        percentile(bet_amount, 0.25) AS bet_amount_p25,
        percentile(bet_amount, 0.50) AS bet_amount_median,
        percentile(bet_amount, 0.75) AS bet_amount_p75,
        STDDEV(bet_amount) AS bet_amount_std,
        MIN(bet_amount) AS bet_amount_min,
        MAX(bet_amount) AS bet_amount_max,

        AVG(delta_bet_amount) AS delta_bet_amount_avg,
        percentile(delta_bet_amount, 0.25) AS delta_bet_amount_p25,
        percentile(delta_bet_amount, 0.50) AS delta_bet_amount_median,
        percentile(delta_bet_amount, 0.75) AS delta_bet_amount_p75,
        STDDEV(delta_bet_amount) AS delta_bet_amount_std,
        MIN(delta_bet_amount) AS delta_bet_amount_min,
        MAX(delta_bet_amount) AS delta_bet_amount_max,
        SUM(CASE WHEN delta_bet_amount > 0 THEN delta_bet_amount ELSE 0 END) AS accum_pos_delta_bet_amount,
        SUM(CASE WHEN delta_bet_amount < 0 THEN delta_bet_amount ELSE 0 END) AS accum_neg_delta_bet_amount,

        AVG(payout) AS payout_avg,
        percentile(payout, 0.25) AS payout_p25,
        percentile(payout, 0.50) AS payout_median,
        percentile(payout, 0.75) AS payout_p75,
        STDDEV(payout) AS payout_std,
        MIN(payout) AS payout_min,
        MAX(payout) AS payout_max,
        SUM(CASE WHEN payout > 0 THEN 1 END) * 1.0 / NULLIF(COUNT(user_id), 0) AS payout_rate,

        AVG(payout * 1.0 / NULLIF(bet_amount, 0)) AS rtp_mean,
        MAX(payout * 1.0 / NULLIF(bet_amount, 0)) AS rtp_max,
        MIN(payout * 1.0 / NULLIF(bet_amount, 0)) AS rtp_min,
        percentile(payout * 1.0 / NULLIF(bet_amount, 0), 0.25) AS rtp_p25,
        percentile(payout * 1.0 / NULLIF(bet_amount, 0), 0.50) AS rtp_median,
        percentile(payout * 1.0 / NULLIF(bet_amount, 0), 0.75) AS rtp_p75,

        AVG(profit) AS profit_avg,
        percentile(profit, 0.25) AS profit_p25,
        percentile(profit, 0.50) AS profit_median,
        percentile(profit, 0.75) AS profit_p75,
        STDDEV(profit) AS profit_std,
        MIN(profit) AS profit_min,
        MAX(profit) AS profit_max,
        SUM(CASE WHEN profit > 0 THEN profit ELSE 0 END) AS accum_pos_profit,
        SUM(CASE WHEN profit < 0 THEN profit ELSE 0 END) AS accum_neg_profit,
        SUM(CASE WHEN profit > 0 THEN 1 ELSE 0 END) * 1.0 / NULLIF(COUNT(user_id), 0) AS profit_rate,

        AVG(delta_payout) AS delta_payout_avg,
        percentile(delta_payout, 0.25) AS delta_payout_p25,
        percentile(delta_payout, 0.50) AS delta_payout_median,
        percentile(delta_payout, 0.75) AS delta_payout_p75,
        STDDEV(delta_payout) AS delta_payout_std,
        MIN(delta_payout) AS delta_payout_min,
        MAX(delta_payout) AS delta_payout_max,

        AVG(balance_after_bet) AS balance_after_bet_avg,
        percentile(balance_after_bet, 0.25) AS balance_after_bet_p25,
        percentile(balance_after_bet, 0.50) AS balance_after_bet_median,
        percentile(balance_after_bet, 0.75) AS balance_after_bet_p75,
        STDDEV(balance_after_bet) AS balance_after_bet_std,
        MIN(balance_after_bet) AS balance_after_bet_min,
        MAX(balance_after_bet) AS balance_after_bet_max,

        SUM(CASE WHEN deposit > 0 THEN 1 ELSE 0 END) AS num_deposit,
        SUM(CASE WHEN deposit > 0 THEN deposit ELSE 0 END) AS accum_deposit,
        SUM(CASE WHEN withdraw > 0 THEN 1 ELSE 0 END) AS num_withdraw,
        SUM(CASE WHEN withdraw > 0 THEN withdraw ELSE 0 END) AS accum_withdraw,

        CAST(AVG(streak) AS BIGINT) AS streak_avg,
        percentile(streak, 0.25) AS streak_p25,
        percentile(streak, 0.50) AS streak_median,
        percentile(streak, 0.75) AS streak_p75,
        STDDEV(streak) AS streak_std,
        MIN(streak) AS streak_min,
        MAX(streak) AS streak_max,

        CAST(AVG(win_streak) AS BIGINT) AS win_streak_avg,
        percentile(win_streak, 0.25) AS win_streak_p25,
        percentile(win_streak, 0.50) AS win_streak_median,
        percentile(win_streak, 0.75) AS win_streak_p75,
        STDDEV(win_streak) AS win_streak_std,
        MIN(win_streak) AS win_streak_min,
        MAX(win_streak) AS win_streak_max,

        CAST(AVG(lose_streak) AS BIGINT) AS lose_streak_avg,
        percentile(lose_streak, 0.25) AS lose_streak_p25,
        percentile(lose_streak, 0.50) AS lose_streak_median,
        percentile(lose_streak, 0.75) AS lose_streak_p75,
        STDDEV(lose_streak) AS lose_streak_std,
        MIN(lose_streak) AS lose_streak_min,
        MAX(lose_streak) AS lose_streak_max
    FROM binned
    GROUP BY user_id, ai_group, math_table_id, session_start_date, session_group, agg_group
)

SELECT
    b.user_id, b.ai_group, b.math_table_id, b.session_start_date, b.session_group, b.agg_group,
    b.activity_date, b.min_created_at, b.max_created_at, b.bet_rounds, b.fg_rounds,
    b.delta_t_seconds_avg, b.delta_t_seconds_p25, b.delta_t_seconds_median, b.delta_t_seconds_p75,
    b.delta_t_seconds_std, b.delta_t_seconds_min, b.delta_t_seconds_max,
    b.delta_t_seconds_nogap_avg, b.delta_t_seconds_nogap_p25, b.delta_t_seconds_nogap_median,
    b.delta_t_seconds_nogap_p75, b.delta_t_seconds_nogap_std, b.delta_t_seconds_nogap_min, b.delta_t_seconds_nogap_max,
    b.bet_amount_avg, b.bet_amount_p25, b.bet_amount_median, b.bet_amount_p75, b.bet_amount_std,
    b.bet_amount_std * 1.0 / NULLIF(b.bet_amount_avg, 0) AS bet_amount_cv,
    b.bet_amount_min,
    b.bet_amount_min * 1.0 / NULLIF(b.bet_amount_avg, 0) AS bet_amount_drawdown_ratio,
    b.bet_amount_max,
    b.bet_amount_max * 1.0 / NULLIF(b.bet_amount_avg, 0) AS bet_amount_spike_ratio,
    b.delta_bet_amount_avg, b.delta_bet_amount_p25, b.delta_bet_amount_median, b.delta_bet_amount_p75,
    b.delta_bet_amount_std,
    COALESCE(b.delta_bet_amount_std * 1.0 / NULLIF(b.bet_amount_avg, 0), 0) AS delta_bet_amount_cv,
    b.delta_bet_amount_min,
    COALESCE(b.delta_bet_amount_min * 1.0 / NULLIF(b.bet_amount_avg, 0), 0) AS delta_bet_amount_drawdown_ratio,
    b.delta_bet_amount_max,
    COALESCE(b.delta_bet_amount_max * 1.0 / NULLIF(b.bet_amount_avg, 0), 0) AS delta_bet_amount_spike_ratio,
    b.accum_pos_delta_bet_amount,
    b.accum_neg_delta_bet_amount,
    b.accum_pos_delta_bet_amount * 1.0 / NULLIF(b.bet_amount_avg, 0) AS accum_pos_delta_bet_amount_ratio,
    b.accum_neg_delta_bet_amount * 1.0 / NULLIF(b.bet_amount_avg, 0) AS accum_neg_delta_bet_amount_ratio,
    b.payout_avg, b.payout_p25, b.payout_median, b.payout_p75, b.payout_std,
    b.payout_std * 1.0 / NULLIF(b.bet_amount_avg, 0) AS payout_cv,
    b.payout_min,
    b.payout_min * 1.0 / NULLIF(b.bet_amount_avg, 0) AS payout_drawdown_ratio,
    b.payout_max,
    b.payout_max * 1.0 / NULLIF(b.bet_amount_avg, 0) AS payout_spike_ratio,
    b.payout_rate,
    b.rtp_mean, b.rtp_max, b.rtp_min, b.rtp_p25, b.rtp_median, b.rtp_p75,
    b.profit_avg, b.profit_p25, b.profit_median, b.profit_p75, b.profit_std,
    b.profit_std * 1.0 / NULLIF(b.bet_amount_avg, 0) AS profit_cv,
    b.profit_min,
    b.profit_min * 1.0 / NULLIF(b.bet_amount_avg, 0) AS min_profit_ratio,
    b.profit_max,
    b.profit_max * 1.0 / NULLIF(b.bet_amount_avg, 0) AS max_profit_ratio,
    b.accum_pos_profit,
    b.accum_pos_profit * 1.0 / NULLIF(b.bet_amount_avg, 0) AS accum_pos_profit_ratio,
    b.accum_neg_profit,
    b.accum_neg_profit * 1.0 / NULLIF(b.bet_amount_avg, 0) AS accum_neg_profit_ratio,
    b.profit_rate,
    b.delta_payout_avg, b.delta_payout_p25, b.delta_payout_median, b.delta_payout_p75, b.delta_payout_std,
    COALESCE(b.delta_payout_std * 1.0 / NULLIF(b.bet_amount_avg, 0), 0) AS delta_payout_cv,
    b.delta_payout_min,
    COALESCE(b.delta_payout_min * 1.0 / NULLIF(b.bet_amount_avg, 0), 0) AS delta_payout_drawdown_ratio,
    b.delta_payout_max,
    COALESCE(b.delta_payout_max * 1.0 / NULLIF(b.bet_amount_avg, 0), 0) AS delta_payout_spike_ratio,
    b.balance_after_bet_avg, b.balance_after_bet_p25, b.balance_after_bet_median, b.balance_after_bet_p75,
    b.balance_after_bet_std,
    b.balance_after_bet_std * 1.0 / NULLIF(b.balance_after_bet_avg, 0) AS balance_after_bet_cv,
    b.balance_after_bet_min,
    b.balance_after_bet_min * 1.0 / NULLIF(b.balance_after_bet_avg, 0) AS balance_after_bet_drawdown_ratio,
    b.balance_after_bet_max,
    b.balance_after_bet_max * 1.0 / NULLIF(b.balance_after_bet_avg, 0) AS balance_after_bet_spike_ratio,
    b.num_deposit, b.accum_deposit,
    b.accum_deposit * 1.0 / NULLIF(b.bet_amount_avg, 0) AS accum_deposit_ratio,
    b.num_withdraw, b.accum_withdraw,
    b.accum_withdraw * 1.0 / NULLIF(b.bet_amount_avg, 0) AS accum_withdraw_ratio,
    COALESCE(b.streak_avg, 0) AS streak_avg,
    COALESCE(b.streak_p25, 0) AS streak_p25,
    COALESCE(b.streak_median, 0) AS streak_median,
    COALESCE(b.streak_p75, 0) AS streak_p75,
    COALESCE(b.streak_std, 0) AS streak_std,
    COALESCE(b.streak_min, 0) AS streak_min,
    COALESCE(b.streak_max, 0) AS streak_max,
    COALESCE(b.win_streak_avg, 0) AS win_streak_avg,
    COALESCE(b.win_streak_p25, 0) AS win_streak_p25,
    COALESCE(b.win_streak_median, 0) AS win_streak_median,
    COALESCE(b.win_streak_p75, 0) AS win_streak_p75,
    COALESCE(b.win_streak_std, 0) AS win_streak_std,
    COALESCE(b.win_streak_min, 0) AS win_streak_min,
    COALESCE(b.win_streak_max, 0) AS win_streak_max,
    COALESCE(b.lose_streak_avg, 0) AS lose_streak_avg,
    COALESCE(b.lose_streak_p25, 0) AS lose_streak_p25,
    COALESCE(b.lose_streak_median, 0) AS lose_streak_median,
    COALESCE(b.lose_streak_p75, 0) AS lose_streak_p75,
    COALESCE(b.lose_streak_std, 0) AS lose_streak_std,
    COALESCE(b.lose_streak_min, 0) AS lose_streak_min,
    COALESCE(b.lose_streak_max, 0) AS lose_streak_max
FROM stats_base AS b
WHERE b.math_table_id IS NOT NULL
