# Deepdive Cluster Analysis Configuration
# This file contains configuration specific to the deepdive clustering project

project_name: "ss01_2026"  # Current analysis environment
work_dir: "output_ss01_wucaishen"  # Base working directory, where local cache of the input data will be saved.
s3_prefix: ""

data_loader:
  cluster_data:  # data to train cluster model.
    bucket: ""  # S3 bucket for input data
    prefix: ""  # S3 prefix for input data
    pattern: ''  # Pattern for grouped data files
    row_filters:  # General row filtering (null to disable filtering)
      currency: ""  # Filter to specific currency
    outlier_threshold: 0  # z score to filter outliers
    clip_threshold: [.25, .75]
    local_cache: "ss01_features_grouped.parquet"

    data_types:
      user_id: "category"
      session_group: "category"
      agg_group: "category"
      rtp_mean: "float64"
      rtp_min: "float64"
      rtp_max: "float64"
      rtp_p25: "float64"
      rtp_median: "float64"
      rtp_p75: "float64"
      bet_amount_min: "float64"
      bet_amount_max: "float64"
      bet_amount_std: "float64"
      bet_amount_cv: "float64"
      bet_amount_avg: "float64"
      bet_amount_p25: "float64"
      bet_amount_median: "float64"
      bet_amount_p75: "float64"
      bet_amount_drawdown_ratio: "float64"
      bet_amount_spike_ratio: "float64"
      delta_bet_amount_min: "float64"
      delta_bet_amount_max: "float64"
      delta_bet_amount_std: "float64"
      delta_bet_amount_cv: "float64"
      delta_bet_amount_avg: "float64"
      delta_bet_amount_p25: "float64"
      delta_bet_amount_median: "float64"
      delta_bet_amount_p75: "float64"
      delta_bet_amount_drawdown_ratio: "float64"
      delta_bet_amount_spike_ratio: "float64"
      accum_pos_delta_bet_amount: "float64"
      accum_neg_delta_bet_amount: "float64"
      accum_pos_delta_bet_amount_ratio: "float64"
      accum_neg_delta_bet_amount_ratio: "float64"
      balance_after_bet_min: "float64"
      balance_after_bet_max: "float64"
      balance_after_bet_avg: "float64"
      balance_after_bet_p25: "float64"
      balance_after_bet_median: "float64"
      balance_after_bet_p75: "float64"
      balance_after_bet_std: "float64"
      balance_after_bet_cv: "float64"
      balance_after_bet_drawdown_ratio: "float64"
      balance_after_bet_spike_ratio: "float64"
      payout_min: "float64"
      payout_max: "float64"
      payout_avg: "float64"
      payout_p25: "float64"
      payout_median: "float64"
      payout_p75: "float64"
      payout_std: "float64"
      payout_cv: "float64"
      payout_drawdown_ratio: "float64"
      payout_spike_ratio: "float64"
      delta_payout_min: "float64"
      delta_payout_max: "float64"
      delta_payout_avg: "float64"
      delta_payout_p25: "float64"
      delta_payout_median: "float64"
      delta_payout_p75: "float64"
      delta_payout_std: "float64"
      delta_payout_cv: "float64"
      delta_payout_drawdown_ratio: "float64"
      delta_payout_spike_ratio: "float64"
      profit_min: "float64"
      profit_max: "float64"
      profit_avg: "float64"
      profit_p25: "float64"
      profit_median: "float64"
      profit_p75: "float64"
      profit_std: "float64"
      profit_cv: "float64"
      min_profit_ratio: "float64"
      max_profit_ratio: "float64"
      accum_pos_profit: "float64"
      accum_pos_profit_ratio: "float64"
      accum_neg_profit: "float64"
      accum_neg_profit_ratio: "float64"
      delta_t_seconds_avg: "float64"
      delta_t_seconds_std: "float64"
      delta_t_seconds_min: "float64"
      delta_t_seconds_max: "float64"
      delta_t_seconds_p25: "float64"
      delta_t_seconds_median: "float64"
      delta_t_seconds_p75: "float64"
      delta_t_seconds_nogap_avg: "float64"
      delta_t_seconds_nogap_std: "float64"
      delta_t_seconds_nogap_min: "float64"
      delta_t_seconds_nogap_max: "float64"
      delta_t_seconds_nogap_p25: "float64"
      delta_t_seconds_nogap_median: "float64"
      delta_t_seconds_nogap_p75: "float64"
      streak_min: "float64"
      streak_max: "float64"
      streak_avg: "float64"
      streak_p25: "float64"
      streak_median: "float64"
      streak_p75: "float64"
      streak_std: "float64"
      win_streak_min: "float64"
      win_streak_max: "float64"
      win_streak_avg: "float64"
      win_streak_p25: "float64"
      win_streak_median: "float64"
      win_streak_p75: "float64"
      win_streak_std: "float64"
      lose_streak_min: "float64"
      lose_streak_max: "float64"
      lose_streak_avg: "float64"
      lose_streak_p25: "float64"
      lose_streak_median: "float64"
      lose_streak_p75: "float64"
      lose_streak_std: "float64"
      num_deposit: "uint32"
      accum_deposit: "float64"
      accum_deposit_ratio: "float64"
      num_withdraw: "uint32"
      accum_withdraw: "float64"
      accum_withdraw_ratio: "float64"

  attach_data:  # data to attach cluster index.
    bucket: ""  # S3 bucket for input data
    prefix: ""  # S3 prefix for input data
    pattern: ''  # Pattern for grouped data files
    row_filters:  # General row filtering (null to disable filtering)
      currency: ""  # Filter to specific currency
    session_length: 40  # stats in grouped data are calculated based on consecutive sessions, sample will be removed if session length not equal to this value for both cluster and attach data.
    local_cache: "ss01_features_enriched.parquet"

    columns_to_read:  # Columns to read from original data files
      - "user_id"
      - "session_group"
      - "agg_group"
      - "account"
      - "cus_account"
      - "currency"
      - "slottype"
      - "basepoint"
      - "delta_t"
      - "delta_bet"
      - "delta_profit"
      - "delta_payout"
      - "streak"
      - "win_streak"
      - "lose_streak"

  merge_on: ["user_id", "session_group", "agg_group"]  # Column used to attach cluster index to attach_data.

output:
  bucket: "bituslabs-team-ai"  # S3 bucket for output data
  prefix: "ss01_analysis_kmeans"  # S3 prefix for output data
  # ONNX model configuration
  onnx:
    opset_version: 19  # ONNX opset version for model conversion

features:
  key_features:  
    - "user_id"
    - "session_group"
    - "agg_group"
  
  skewed_features:  # Features that need power transformation
    - "rtp_mean"
    - "rtp_min"
    - "rtp_max"
    - "rtp_p25"
    - "rtp_median"
    - "rtp_p75"
    - "bet_amount_min"
    - "bet_amount_max"
    - "bet_amount_std"
    - "bet_amount_cv"
    - "bet_amount_avg"
    - "bet_amount_p25"
    - "bet_amount_median"
    - "bet_amount_p75"
    - "bet_amount_drawdown_ratio"
    - "bet_amount_spike_ratio"
    - "delta_bet_amount_min"
    - "delta_bet_amount_max"
    - "delta_bet_amount_std"
    - "delta_bet_amount_cv"
    - "delta_bet_amount_avg"
    - "delta_bet_amount_p25"
    - "delta_bet_amount_median"
    - "delta_bet_amount_p75"
    - "delta_bet_amount_drawdown_ratio"
    - "delta_bet_amount_spike_ratio"
    - "accum_pos_delta_bet_amount"
    - "accum_neg_delta_bet_amount"
    - "accum_pos_delta_bet_amount_ratio"
    - "accum_neg_delta_bet_amount_ratio"
    - "balance_after_bet_min"
    - "balance_after_bet_max"
    - "balance_after_bet_avg"
    - "balance_after_bet_p25"
    - "balance_after_bet_median"
    - "balance_after_bet_p75"
    - "balance_after_bet_std"
    - "balance_after_bet_cv"
    - "balance_after_bet_drawdown_ratio"
    - "balance_after_bet_spike_ratio"
    - "payout_min"
    - "payout_max"
    - "payout_avg"
    - "payout_p25"
    - "payout_median"
    - "payout_p75"
    - "payout_std"
    - "payout_cv"
    - "payout_drawdown_ratio"
    - "payout_spike_ratio"
    - "delta_payout_min"
    - "delta_payout_max"
    - "delta_payout_avg"
    - "delta_payout_p25"
    - "delta_payout_median"
    - "delta_payout_p75"
    - "delta_payout_std"
    - "delta_payout_cv"
    - "delta_payout_drawdown_ratio"
    - "delta_payout_spike_ratio"
    - "profit_min"
    - "profit_max"
    - "profit_avg"
    - "profit_p25"
    - "profit_median"
    - "profit_p75"
    - "profit_std"
    - "profit_cv"
    - "min_profit_ratio"
    - "max_profit_ratio"
    - "accum_pos_profit"
    - "accum_pos_profit_ratio"
    - "accum_neg_profit"
    - "accum_neg_profit_ratio"
    - "delta_t_seconds_avg"
    - "delta_t_seconds_std"
    - "delta_t_seconds_min"
    - "delta_t_seconds_max"
    - "delta_t_seconds_p25"
    - "delta_t_seconds_median"
    - "delta_t_seconds_p75"
    - "delta_t_seconds_nogap_avg"
    - "delta_t_seconds_nogap_std"
    - "delta_t_seconds_nogap_min"
    - "delta_t_seconds_nogap_max"
    - "delta_t_seconds_nogap_p25"
    - "delta_t_seconds_nogap_median"
    - "delta_t_seconds_nogap_p75"
    - "streak_min"
    - "streak_max"
    - "streak_avg"
    - "streak_p25"
    - "streak_median"
    - "streak_p75"
    - "streak_std"
    - "win_streak_min"
    - "win_streak_max"
    - "win_streak_avg"
    - "win_streak_p25"
    - "win_streak_median"
    - "win_streak_p75"
    - "win_streak_std"
    - "lose_streak_min"
    - "lose_streak_max"
    - "lose_streak_avg"
    - "lose_streak_p25"
    - "lose_streak_median"
    - "lose_streak_p75"
    - "lose_streak_std"
    - "num_deposit"
    - "accum_deposit"
    - "accum_deposit_ratio"
    - "num_withdraw"
    - "accum_withdraw"
    - "accum_withdraw_ratio"
  
  normal_features:  # Features that don't need transformation
    - "fg_rounds"
    - "payout_rate"
    - "profit_rate"

feature_selection:
  correlation_threshold: 0.9  # Threshold for removing highly correlated features
  variance_threshold: 0.01  # Threshold for removing low-variance features

elbow_method:
  top_features: [15, 20, 25, 30, 35, 40, 45, 50]  # Range of k values to test
  k_range: [2, 3, 4, 5, 6, 7]  # Range of k values to test

cluster_analysis:
  random_state: 42  # Random state for reproducible results
  n_init: 10  # Number of initializations for K-means algorithm
  n_clusters: 3  # Default number of clusters for K-means
  top_features: 40  # Default number of top features to use

pipeline:
  elbow_method: true  # Run elbow method analysis
  cluster_analysis: false  # Run cluster analysis with selected features and n_clusters  
  fit_cluster_model: false  # Apply trained model to new data
  attach_cluster_label: false  # Attach cluster indices to original data
  get_cluster_stats: false 
  upload_result_to_s3: false  



