/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/data/config/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description API endpoint: GET /api/data/config/{config_id} — resolved config for one game.
         *
         *     Drives which tabs, metric groups, and date granularities the dashboard
         *     shows. This is also the snapshot the agent reads to decide which config to
         *     load and which tab to open for a natural-language data request.
         */
        get: operations["get_config_api_data_config__config_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Configs
         * @description API endpoint: GET /api/data/configs — powers the game/config picker in the SPA top bar.
         *
         *     Returns one entry per ``dashboard_config-*.yaml`` in ``DASHBOARD_CONFIG_DIR``;
         *     the id is the filename minus the ``dashboard_config-`` prefix (e.g. ``ss01``,
         *     ``fishhunter``).
         */
        get: operations["list_configs_api_data_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Series
         * @description API endpoint: POST /api/data/series — metric time-series for a chart.
         *
         *     Returns date-aligned series the frontend encodes into an ECharts chart.
         *     Metrics not present in the source parquet come back in ``missing`` rather
         *     than failing the request, so the UI can flag them.
         */
        post: operations["post_series_api_data_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description API endpoint: GET /api/health — ALB/uptime health check for the dashboard_api service.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigDetail */
        ConfigDetail: {
            /** Date Col */
            date_col: string;
            /** Granularities */
            granularities: ("day" | "week" | "month")[];
            /** Group Col */
            group_col: string;
            /** Groups */
            groups: components["schemas"]["MetricGroup"][];
            /** Id */
            id: string;
            /** Tabs */
            tabs: string[];
            /** Title */
            title: string;
            /** User Group Cols */
            user_group_cols: string[];
        };
        /** ConfigList */
        ConfigList: {
            /** Configs */
            configs: components["schemas"]["ConfigSummary"][];
        };
        /** ConfigSummary */
        ConfigSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricGroup */
        MetricGroup: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Metrics */
            metrics: string[];
        };
        /** Series */
        Series: {
            /** Name */
            name: string;
            /** Y */
            y: (number | null)[];
        };
        /** SeriesRequest */
        SeriesRequest: {
            /** Config */
            config: string;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Metrics */
            metrics: string[];
        };
        /** SeriesResponse */
        SeriesResponse: {
            /** Config */
            config: string;
            /** Date Col */
            date_col: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Missing */
            missing: string[];
            /** Series */
            series: components["schemas"]["Series"][];
            /** X */
            x: (string | null)[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_data_config__config_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_configs_api_data_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigList"];
                };
            };
        };
    };
    post_series_api_data_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
