/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/data/config/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description API endpoint: GET /api/data/config/{config_id} — resolved config for one game.
         *
         *     Drives which tabs, metric groups, and date granularities the dashboard
         *     shows. This is also the snapshot the agent reads to decide which config to
         *     load and which tab to open for a natural-language data request.
         */
        get: operations["get_config_api_data_config__config_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Configs
         * @description API endpoint: GET /api/data/configs — powers the game/config picker in the SPA top bar.
         *
         *     Returns one entry per ``dashboard_config-*.yaml`` in ``DASHBOARD_CONFIG_DIR``;
         *     the id is the filename minus the ``dashboard_config-`` prefix (e.g. ``ss01``,
         *     ``fishhunter``).
         */
        get: operations["list_configs_api_data_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/date-bounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Date Bounds
         * @description API endpoint: GET /api/data/date-bounds — min/max date in the source data.
         *
         *     The Stats-by-Date tab seeds its default window (last 30 days) from ``max``.
         */
        get: operations["get_date_bounds_api_data_date_bounds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/deepdive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Deepdive
         * @description API endpoint: POST /api/data/deepdive — Deep Dive tab.
         *
         *     Pre-binned histograms or a Pearson correlation matrix over the selected
         *     metrics, per (cohort × date-range), for the derived or user-level panel.
         */
        post: operations["post_deepdive_api_data_deepdive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/deepdive-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deepdive Metrics
         * @description API endpoint: GET /api/data/deepdive-metrics — metric lists for the Deep
         *     Dive panel pickers (derived = group-level DataMetrics, user = raw user_* columns).
         */
        get: operations["get_deepdive_metrics_api_data_deepdive_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/group-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Group Distribution
         * @description API endpoint: POST /api/data/group-distribution — Stats-by-Group tab.
         *
         *     Per (cohort × date-range), the metric's distribution as a 5-number summary +
         *     mean/bootstrap-CI, so the frontend renders a box plot or a bar chart.
         */
        post: operations["post_group_distribution_api_data_group_distribution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/group-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Group Values
         * @description API endpoint: GET /api/data/group-values — distinct cohort values per
         *     user-group column, for the Stats-by-Date cohort pickers.
         *
         *     ``values`` is the full (cached) vocabulary so labels never disappear when
         *     the date range moves; with ``start``/``end`` the response also carries
         *     ``available`` — the subset present in that range — which the pickers use
         *     to gray out values with no data in view.
         *
         *     Returns ``{}`` when the config defines no user_group columns. Reads the same
         *     user-level parquet as ``/series``.
         */
        get: operations["get_group_values_api_data_group_values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Series
         * @description API endpoint: POST /api/data/series — metric time-series for a chart.
         *
         *     Returns date-aligned series the frontend encodes into an ECharts chart.
         *     Metrics not present in the source parquet come back in ``missing`` rather
         *     than failing the request, so the UI can flag them.
         */
        post: operations["post_series_api_data_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/summary-table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Summary Table
         * @description API endpoint: POST /api/data/summary-table — Summary-table tab.
         *
         *     One grid for all metrics at once: rows are metrics (grouped by the config's
         *     metric groups), columns are the selected cohort × date-range combinations.
         *     Each cell is a metric's mean/median/quartiles for that column; the frontend
         *     flags one column as the reference and renders the rest as ``value (±%)``.
         *     With ``pvalues=true`` each row also carries a Welch t-test (2 columns) or
         *     one-way ANOVA (3+) p-value.
         */
        post: operations["post_summary_table_api_data_summary_table_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description API endpoint: GET /api/health — ALB/uptime health check for the dashboard_api service.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Description
         * @description API endpoint: POST /api/report/description — proxy to ai_agent.
         *
         *     Forwards {data_summary, existing_description, references, language, model}
         *     to the agent service's LLM generation; in prod the ALB routes /api/report/*
         *     here, so this hop keeps the contract while the LLM stays on ai_agent.
         */
        post: operations["post_description_api_report_description_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Export
         * @description API endpoint: POST /api/report/export — write the report to Confluence.
         *
         *     Receives client-rendered ECharts PNGs (base64) + descriptions + summary +
         *     references; attaches the images and idempotently replaces the
         *     "Dashboard Report" region of the target page (content above it preserved).
         */
        post: operations["post_export_api_report_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post References
         * @description API endpoint: POST /api/report/references — fetch reference pages.
         *
         *     Resolves Confluence URLs to {url, title, text} (cached server-side) for the
         *     reference pills and as LLM context; non-Confluence URLs come back with empty
         *     text but are still listed.
         */
        post: operations["post_references_api_report_references_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/spec/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Spec
         * @description API endpoint: GET /api/report/spec/{name} — load one saved report spec.
         */
        get: operations["get_spec_api_report_spec__name__get"];
        /**
         * Put Spec
         * @description API endpoint: PUT /api/report/spec/{name} — save a report spec to S3.
         */
        put: operations["put_spec_api_report_spec__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Specs
         * @description API endpoint: GET /api/report/specs — list saved report specs.
         */
        get: operations["get_specs_api_report_specs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Summary
         * @description API endpoint: POST /api/report/summary — proxy to ai_agent (see /description).
         */
        post: operations["post_summary_api_report_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Views
         * @description API endpoint: GET /api/views — list saved dashboard view snapshots.
         */
        get: operations["get_views_api_views_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/views/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get View
         * @description API endpoint: GET /api/views/{name} — load one saved view snapshot (opaque JSON).
         */
        get: operations["get_view_api_views__name__get"];
        /**
         * Put View
         * @description API endpoint: PUT /api/views/{name} — save a dashboard view snapshot.
         *
         *     Returns the sanitized name, the s3:// path written (surfaced to the user),
         *     and the refreshed view list.
         */
        put: operations["put_view_api_views__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClipOpts */
        ClipOpts: {
            /**
             * Enable
             * @default false
             */
            enable: boolean;
            /** Max */
            max?: number | null;
            /** Min */
            min?: number | null;
        };
        /** ConfigDetail */
        ConfigDetail: {
            /** Date Col */
            date_col: string;
            /** Granularities */
            granularities: ("day" | "week" | "month")[];
            /** Group Col */
            group_col: string;
            /** Groups */
            groups: components["schemas"]["MetricGroup"][];
            /** Id */
            id: string;
            /** Lifecycle Col */
            lifecycle_col?: string | null;
            /** Period Total Col */
            period_total_col?: string | null;
            /**
             * Period Total Defaults
             * @default {}
             */
            period_total_defaults: {
                [key: string]: components["schemas"]["RangeGroup"][];
            };
            /** Period Total Name */
            period_total_name?: string | null;
            /** Range Group Col */
            range_group_col?: string | null;
            /**
             * Range Group Defaults
             * @default []
             */
            range_group_defaults: components["schemas"]["RangeGroup"][];
            /** Range Group Name */
            range_group_name?: string | null;
            /**
             * Range Group Values
             * @default []
             */
            range_group_values: number[];
            /** Tabs */
            tabs: string[];
            /** Title */
            title: string;
            /** User Group Cols */
            user_group_cols: string[];
        };
        /** ConfigList */
        ConfigList: {
            /** Configs */
            configs: components["schemas"]["ConfigSummary"][];
        };
        /** ConfigSummary */
        ConfigSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** CorrMatrix */
        CorrMatrix: {
            /** Cohort */
            cohort: string;
            /** Corr */
            corr: (number | null)[][];
            /** Metrics */
            metrics: string[];
            /** Range Index */
            range_index: number;
            /** Range Label */
            range_label: string;
        };
        /** DateBounds */
        DateBounds: {
            /** Config */
            config: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Max */
            max: string | null;
            /** Min */
            min: string | null;
        };
        /** DateFigureSource */
        DateFigureSource: {
            /** Cohort Selection */
            cohort_selection?: {
                [key: string]: string[];
            };
            /** Config */
            config: string;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stats-by-date";
            /** Left */
            left?: string[];
            /**
             * Log
             * @default false
             */
            log: boolean;
            /** Panel Id */
            panel_id: string;
            /** Right */
            right?: string[];
            /**
             * Threshold
             * @default 10
             */
            threshold: number;
        };
        /** DateRange */
        DateRange: {
            /** End */
            end?: string | null;
            /** Start */
            start?: string | null;
        };
        /** DeepdiveFigureSource */
        DeepdiveFigureSource: {
            clip?: components["schemas"]["ClipOpts"];
            /** Cohort Selection */
            cohort_selection?: {
                [key: string]: string[];
            };
            /** Config */
            config: string;
            filter?: components["schemas"]["FilterOpts"];
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stats-deepdive";
            /**
             * Log Y
             * @default false
             */
            log_y: boolean;
            /** Metrics */
            metrics?: string[];
            /**
             * Mode
             * @default histogram
             * @enum {string}
             */
            mode: "histogram" | "heatmap" | "scatter";
            /**
             * Nbins
             * @default 50
             */
            nbins: number;
            /**
             * Normalize
             * @default false
             */
            normalize: boolean;
            /** Outliers Std */
            outliers_std?: number | null;
            /**
             * Panel
             * @enum {string}
             */
            panel: "derived" | "user";
            /** Ranges */
            ranges?: components["schemas"]["DateRange"][];
            /**
             * Scatter Log X
             * @default false
             */
            scatter_log_x: boolean;
            /**
             * Scatter Log Y
             * @default false
             */
            scatter_log_y: boolean;
        };
        /** DeepdiveMetrics */
        DeepdiveMetrics: {
            /** Config */
            config: string;
            /** Derived */
            derived: string[];
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** User */
            user: string[];
        };
        /** DeepdiveRequest */
        DeepdiveRequest: {
            clip?: components["schemas"]["ClipOpts"];
            /** Config */
            config: string;
            filter?: components["schemas"]["FilterOpts"];
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Group Values */
            group_values?: {
                [key: string]: string[];
            };
            /** Lifecycle Groups */
            lifecycle_groups?: components["schemas"]["LifecycleGroup"][] | null;
            /** Metrics */
            metrics: string[];
            /**
             * Mode
             * @enum {string}
             */
            mode: "histogram" | "heatmap" | "scatter";
            /**
             * Nbins
             * @default 50
             */
            nbins: number;
            /**
             * Normalize
             * @default false
             */
            normalize: boolean;
            /** Outliers Std */
            outliers_std?: number | null;
            /**
             * Panel
             * @enum {string}
             */
            panel: "derived" | "user";
            /** Range Groups */
            range_groups?: components["schemas"]["RangeGroup"][] | null;
            /** Ranges */
            ranges: components["schemas"]["DateRange"][];
        };
        /** DeepdiveResponse */
        DeepdiveResponse: {
            /** Config */
            config: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Heatmaps */
            heatmaps: components["schemas"]["CorrMatrix"][];
            /** Histograms */
            histograms: components["schemas"]["HistogramSeries"][];
            /** Missing */
            missing: string[];
            /**
             * Mode
             * @enum {string}
             */
            mode: "histogram" | "heatmap" | "scatter";
            /**
             * Panel
             * @enum {string}
             */
            panel: "derived" | "user";
            /** Scatters */
            scatters: components["schemas"]["ScatterSeries"][];
        };
        /** ExportFigure */
        ExportFigure: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Html */
            html?: string | null;
            /** Png Base64 */
            png_base64?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ExportRequest */
        ExportRequest: {
            /** Confluence Url */
            confluence_url: string;
            /** Figures */
            figures: components["schemas"]["ExportFigure"][];
            /** References */
            references?: components["schemas"]["ReportReference"][];
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** ExportResponse */
        ExportResponse: {
            /** Figures Uploaded */
            figures_uploaded: number;
            /** Page Id */
            page_id: string;
            /** Page Version */
            page_version: number | null;
        };
        /** FilterOpts */
        FilterOpts: {
            /**
             * Enable
             * @default false
             */
            enable: boolean;
            /** Max */
            max?: number | null;
            /** Min */
            min?: number | null;
        };
        /** GenerateProxyResponse */
        GenerateProxyResponse: {
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Message */
            message: string;
            /** Status */
            status: string;
            /** Text */
            text: string;
        };
        /** GroupDistributionRequest */
        GroupDistributionRequest: {
            clip?: components["schemas"]["ClipOpts"];
            /** Config */
            config: string;
            filter?: components["schemas"]["FilterOpts"];
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Group Values */
            group_values?: {
                [key: string]: string[];
            };
            /** Lifecycle Groups */
            lifecycle_groups?: components["schemas"]["LifecycleGroup"][] | null;
            /** Metric */
            metric: string;
            /** Range Groups */
            range_groups?: components["schemas"]["RangeGroup"][] | null;
            /** Ranges */
            ranges: components["schemas"]["DateRange"][];
        };
        /** GroupDistributionResponse */
        GroupDistributionResponse: {
            /** Config */
            config: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Metric */
            metric: string;
            /** Missing */
            missing: boolean;
            /** Stats */
            stats: components["schemas"]["GroupStat"][];
        };
        /** GroupFigureSource */
        GroupFigureSource: {
            clip?: components["schemas"]["ClipOpts"];
            /** Cohort Selection */
            cohort_selection?: {
                [key: string]: string[];
            };
            /** Config */
            config: string;
            filter?: components["schemas"]["FilterOpts"];
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stats-by-group";
            /** Metric */
            metric: string;
            /**
             * Mode
             * @default bar
             * @enum {string}
             */
            mode: "box" | "bar";
            /** Panel Id */
            panel_id: string;
            /** Ranges */
            ranges?: components["schemas"]["DateRange"][];
        };
        /** GroupStat */
        GroupStat: {
            /** Ci Lower */
            ci_lower: number | null;
            /** Ci Upper */
            ci_upper: number | null;
            /** Cohort */
            cohort: string;
            /** Max */
            max: number | null;
            /** Mean */
            mean: number | null;
            /** Median */
            median: number | null;
            /** Min */
            min: number | null;
            /** N */
            n: number;
            /** Q1 */
            q1: number | null;
            /** Q3 */
            q3: number | null;
            /** Range Index */
            range_index: number;
            /** Range Label */
            range_label: string;
            /** Std */
            std: number | null;
        };
        /** GroupValues */
        GroupValues: {
            /** Available */
            available?: {
                [key: string]: string[];
            } | null;
            /** Config */
            config: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Values */
            values: {
                [key: string]: string[];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramSeries */
        HistogramSeries: {
            /** Bin Edges */
            bin_edges: number[];
            /** Cohort */
            cohort: string;
            /** Counts */
            counts: number[];
            /** Metric */
            metric: string;
            /** Range Index */
            range_index: number;
            /** Range Label */
            range_label: string;
        };
        /**
         * LifecycleGroup
         * @description One user-defined lifecycle cohort: users whose activity falls in the
         *     HALF-OPEN period range [start, end) after their first bet — start
         *     inclusive, end exclusive, so adjacent groups sharing a boundary (0→3,
         *     3→7, 7→max) tile with no gap and no double-count. The period unit IS the
         *     request's granularity — days on daily data, calendar weeks on weekly data,
         *     calendar months on monthly data (week/month rows aggregate a whole period,
         *     so sub-period day ranges would slice by start weekday, not user age).
         *
         *     Dashboard feature: the global "Lifecycle groups" picker above the tab bar.
         *     ``end=None`` means open-ended (start and later). The label "all" is a
         *     sentinel meaning no filter (the full population), mirroring group_values.
         *     Ranges may overlap (e.g. compare day 0→3 against day 0→7).
         */
        LifecycleGroup: {
            /** End */
            end?: number | null;
            /** Label */
            label: string;
            /** Start */
            start: number;
        };
        /** MetricGroup */
        MetricGroup: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Metrics */
            metrics: string[];
        };
        /**
         * RangeGroup
         * @description One user-defined value-range cohort over a range dimension: rows with
         *     min <= value <= max — both ends INCLUSIVE, ``max=None`` open-ended.
         *
         *     Dashboard feature: the "Fish level" / "Bet level" / "Total bet" pickers
         *     next to Lifecycle groups. ``column`` says which range dimension the group
         *     addresses — the stored range column (``range_group_col``) when omitted
         *     (pre-multi-picker clients), or the derived period-total column
         *     (``period_total_col``, one total per user × period). The label "all" is
         *     the no-filter sentinel; ranges may overlap.
         */
        RangeGroup: {
            /** Column */
            column?: string | null;
            /** Label */
            label: string;
            /** Max */
            max?: number | null;
            /** Min */
            min: number;
        };
        /** ReferencesRequest */
        ReferencesRequest: {
            /** Urls */
            urls: string[];
        };
        /** ReferencesResponse */
        ReferencesResponse: {
            /** References */
            references: {
                [key: string]: string;
            }[];
        };
        /** ReportFigure */
        "ReportFigure-Input": {
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            /**
             * Inherit Period
             * @default true
             */
            inherit_period: boolean;
            /** Source */
            source: components["schemas"]["DateFigureSource"] | components["schemas"]["GroupFigureSource"] | components["schemas"]["DeepdiveFigureSource"] | components["schemas"]["SummaryTableFigureSource-Input"];
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ReportFigure */
        "ReportFigure-Output": {
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            /**
             * Inherit Period
             * @default true
             */
            inherit_period: boolean;
            /** Source */
            source: components["schemas"]["DateFigureSource"] | components["schemas"]["GroupFigureSource"] | components["schemas"]["DeepdiveFigureSource"] | components["schemas"]["SummaryTableFigureSource-Output"];
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ReportReference */
        ReportReference: {
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Status */
            status?: string | null;
            /** Text */
            text?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /** ReportSpec */
        "ReportSpec-Input": {
            /**
             * Confluence Url
             * @default
             */
            confluence_url: string;
            /** Figures */
            figures?: components["schemas"]["ReportFigure-Input"][];
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "zh-Hans" | "zh-Hant";
            period?: components["schemas"]["DateRange"] | null;
            /** References */
            references?: components["schemas"]["ReportReference"][];
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** View */
            view?: string | null;
        };
        /** ReportSpec */
        "ReportSpec-Output": {
            /**
             * Confluence Url
             * @default
             */
            confluence_url: string;
            /** Figures */
            figures?: components["schemas"]["ReportFigure-Output"][];
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "zh-Hans" | "zh-Hant";
            period?: components["schemas"]["DateRange"] | null;
            /** References */
            references?: components["schemas"]["ReportReference"][];
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** View */
            view?: string | null;
        };
        /** ReportSpecList */
        ReportSpecList: {
            /** Specs */
            specs: string[];
        };
        /** ReportSpecSaveResult */
        ReportSpecSaveResult: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Specs */
            specs: string[];
        };
        /** ScatterSeries */
        ScatterSeries: {
            /** Cohort */
            cohort: string;
            /** Metrics */
            metrics: string[];
            /** Points */
            points: number[][];
            /** Range Index */
            range_index: number;
            /** Range Label */
            range_label: string;
        };
        /** Series */
        Series: {
            /** Additive */
            additive: boolean;
            /** Cohort */
            cohort: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "computed" | "user" | "raw";
            /** Lower */
            lower: (number | null)[];
            /** Metric */
            metric: string;
            /** Range Index */
            range_index?: number | null;
            /** Range Label */
            range_label?: string | null;
            /** Upper */
            upper: (number | null)[];
            /** X */
            x: string[];
            /** Y */
            y: (number | null)[];
        };
        /** SeriesRequest */
        SeriesRequest: {
            /** Config */
            config: string;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Group Values */
            group_values?: {
                [key: string]: string[];
            };
            /** Lifecycle Groups */
            lifecycle_groups?: components["schemas"]["LifecycleGroup"][] | null;
            /** Metrics */
            metrics: string[];
            /** Range Groups */
            range_groups?: components["schemas"]["RangeGroup"][] | null;
            /** Ranges */
            ranges?: components["schemas"]["DateRange"][] | null;
        };
        /** SeriesResponse */
        SeriesResponse: {
            /** Config */
            config: string;
            /** Date Col */
            date_col: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Missing */
            missing: string[];
            /** Series */
            series: components["schemas"]["Series"][];
        };
        /** SummaryCell */
        SummaryCell: {
            /** Max */
            max: number | null;
            /** Mean */
            mean: number | null;
            /** Median */
            median: number | null;
            /** Min */
            min: number | null;
            /** N */
            n: number;
            /** Q1 */
            q1: number | null;
            /** Q3 */
            q3: number | null;
            /** Std */
            std: number | null;
        };
        /** SummaryColumn */
        SummaryColumn: {
            /** Cohort */
            cohort: string;
            /** Key */
            key: string;
            /** Range Index */
            range_index: number;
            /** Range Label */
            range_label: string;
        };
        /** SummaryMetricOption */
        SummaryMetricOption: {
            clip?: components["schemas"]["ClipOpts"];
            /**
             * Log
             * @default false
             */
            log: boolean;
        };
        /** SummaryRow */
        SummaryRow: {
            /** Cells */
            cells: (components["schemas"]["SummaryCell"] | null)[];
            /** Group Id */
            group_id: string;
            /** Group Label */
            group_label: string;
            /** Metric */
            metric: string;
            /**
             * Missing
             * @default false
             */
            missing: boolean;
            /** Pvalue */
            pvalue?: number | null;
            /** Test */
            test?: string | null;
        };
        /** SummaryTableFigureSource */
        "SummaryTableFigureSource-Input": {
            /** Cohort Selection */
            cohort_selection?: {
                [key: string]: string[];
            };
            /** Config */
            config: string;
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "summary-table";
            /** Metric Options */
            metric_options?: {
                [key: string]: components["schemas"]["SummaryMetricOption"];
            };
            /** Metrics */
            metrics?: {
                [key: string]: string[];
            };
            /**
             * Pvalues
             * @default false
             */
            pvalues: boolean;
            /** Ranges */
            ranges?: components["schemas"]["DateRange"][];
            /** Reference Key */
            reference_key?: string | null;
            /** Stats */
            stats?: string[];
        };
        /** SummaryTableFigureSource */
        "SummaryTableFigureSource-Output": {
            /** Cohort Selection */
            cohort_selection?: {
                [key: string]: string[];
            };
            /** Config */
            config: string;
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "summary-table";
            /** Metric Options */
            metric_options?: {
                [key: string]: components["schemas"]["SummaryMetricOption"];
            };
            /** Metrics */
            metrics?: {
                [key: string]: string[];
            };
            /**
             * Pvalues
             * @default false
             */
            pvalues: boolean;
            /** Ranges */
            ranges?: components["schemas"]["DateRange"][];
            /** Reference Key */
            reference_key?: string | null;
            /** Stats */
            stats?: string[];
        };
        /** SummaryTableRequest */
        SummaryTableRequest: {
            /** Config */
            config: string;
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Group Values */
            group_values?: {
                [key: string]: string[];
            };
            /** Lifecycle Groups */
            lifecycle_groups?: components["schemas"]["LifecycleGroup"][] | null;
            /** Metric Options */
            metric_options?: {
                [key: string]: components["schemas"]["SummaryMetricOption"];
            };
            /**
             * Pvalues
             * @default false
             */
            pvalues: boolean;
            /** Range Groups */
            range_groups?: components["schemas"]["RangeGroup"][] | null;
            /** Ranges */
            ranges: components["schemas"]["DateRange"][];
        };
        /** SummaryTableResponse */
        SummaryTableResponse: {
            /** Columns */
            columns: components["schemas"]["SummaryColumn"][];
            /** Config */
            config: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            /** Rows */
            rows: components["schemas"]["SummaryRow"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViewList */
        ViewList: {
            /** Views */
            views: string[];
        };
        /** ViewSaveResult */
        ViewSaveResult: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Views */
            views: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_data_config__config_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_configs_api_data_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigList"];
                };
            };
        };
    };
    get_date_bounds_api_data_date_bounds_get: {
        parameters: {
            query: {
                config: string;
                granularity?: "day" | "week" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DateBounds"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_deepdive_api_data_deepdive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeepdiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepdiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deepdive_metrics_api_data_deepdive_metrics_get: {
        parameters: {
            query: {
                config: string;
                granularity?: "day" | "week" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepdiveMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_group_distribution_api_data_group_distribution_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupDistributionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_group_values_api_data_group_values_get: {
        parameters: {
            query: {
                config: string;
                granularity?: "day" | "week" | "month";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupValues"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_series_api_data_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_summary_table_api_data_summary_table_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryTableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    post_description_api_report_description_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateProxyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_export_api_report_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_references_api_report_references_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferencesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spec_api_report_spec__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSpec-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_spec_api_report_spec__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportSpec-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSpecSaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_specs_api_report_specs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSpecList"];
                };
            };
        };
    };
    post_summary_api_report_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateProxyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_views_api_views_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewList"];
                };
            };
        };
    };
    get_view_api_views__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_view_api_views__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewSaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
