"""
prepare data statistics of wucaishen cluster data to support GAI simulation. This statistics defines the start state of
the simulation model.
The cluster data is generated by sagemaker jobs cluster_analysis_*.py

bet statistics for basepoint, all account (bet amount) values with its frequency.
"""

import datetime
import json
import os
from collections import Counter
from typing import Any

import numpy as np
from scipy.stats import skew
from sklearn.preprocessing import StandardScaler

from bituslabs_ds.config import LOCAL_ROOT, S3_BUCKET, setup_logging
from bituslabs_ds.s3_utils import read_files, upload_file_to_s3

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = LOCAL_ROOT / "jobs/output_deepdive/cluster_stats/"

setup_logging(f"{LOCAL_ROOT}/jobs/log/analysis_gai_simulation_cluster_stats.log")


def convert_numpy_types(obj):
    """Convert NumPy types to native Python types for JSON serialization."""
    if isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, Counter):
        return dict[Any, int](obj)
    elif isinstance(obj, dict):
        return {key: convert_numpy_types(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [convert_numpy_types(item) for item in obj]
    else:
        return obj


year = 2025
enriched_data_with_clusters = [
    "s3://bituslabs-team-ai/deepdive_analysis_kmeans/cny_8_month_2025-10-20_17-41-50/output/enriched_data_cluster_0.parquet",
    "s3://bituslabs-team-ai/deepdive_analysis_kmeans/cny_8_month_2025-10-20_17-41-50/output/enriched_data_cluster_1.parquet",
    "s3://bituslabs-team-ai/deepdive_analysis_kmeans/cny_8_month_2025-10-20_17-41-50/output/enriched_data_cluster_2.parquet",
]

# year = 2024
# enriched_data_with_clusters = [
#     "s3://bituslabs-team-ai/ds-data-kmeans/wucaishen_with_cluster_2024_0.csv",
#     "s3://bituslabs-team-ai/ds-data-kmeans/wucaishen_with_cluster_2024_1.csv",
#     "s3://bituslabs-team-ai/ds-data-kmeans/wucaishen_with_cluster_2024_2.csv",
# ]

# year = 2025
# enriched_data_with_clusters = [
#     "s3://bituslabs-team-ai/ds-data-kmeans/2025_2025-06-18_16-43-44/wucaishen_with_cluster_2025_0.csv",
#     "s3://bituslabs-team-ai/ds-data-kmeans/2025_2025-06-18_16-43-44/wucaishen_with_cluster_2025_1.csv",
#     "s3://bituslabs-team-ai/ds-data-kmeans/2025_2025-06-18_16-43-44/wucaishen_with_cluster_2025_2.csv",
# ]

scaler = StandardScaler()
cluster_stats = {}
for cluster_index in range(len(enriched_data_with_clusters)):
    data = read_files(
        [enriched_data_with_clusters[cluster_index]],
        local_cache_path=f"{OUTPUT_DIR}/enriched_with_clusters_{year}_{cluster_index}.parquet",
        columns=["basepoint", "account"],
    )

    scaler.fit(data["basepoint"].to_frame())

    _basepoint_clean = data["basepoint"].dropna()
    stats = {
        "basepoint_mean": data["basepoint"].mean(),
        "basepoint_min": data["basepoint"].min(),
        "basepoint_max": data["basepoint"].max(),
        "basepoint_p5": np.percentile(_basepoint_clean, 5) if _basepoint_clean.size > 0 else None,
        "basepoint_p25": np.percentile(_basepoint_clean, 25) if _basepoint_clean.size > 0 else None,
        "basepoint_p75": np.percentile(_basepoint_clean, 75) if _basepoint_clean.size > 0 else None,
        "basepoint_p95": np.percentile(_basepoint_clean, 95) if _basepoint_clean.size > 0 else None,
        "basepoint_median": data["basepoint"].median(),
        "basepoint_skewness": skew(_basepoint_clean),
        "basepoint_std": data["basepoint"].std(),
        "basepoint_count": len(data["basepoint"]),
        "basepoint_nan_count": len(data["basepoint"]) - len(_basepoint_clean),
        "basepoint_nan_ratio": (len(data["basepoint"]) - len(_basepoint_clean)) / len(data["basepoint"]),
        "basepoint_less_than_0_count": (_basepoint_clean < 0).sum(),
        "basepoint_less_than_0_ratio": (_basepoint_clean < 0).sum() / len(data["basepoint"]),
        "basepoint_scaler_mean": scaler.mean_[0],
        "basepoint_scaler_std": np.sqrt(scaler.var_[0]),
        "account_counter": Counter(data["account"]),
    }
    cluster_stats[f"cluster_{cluster_index}"] = stats

# Convert NumPy types to native Python types for JSON serialization
cluster_stats_serializable = convert_numpy_types(cluster_stats)
json.dump(cluster_stats_serializable, open(f"{OUTPUT_DIR}/cluster_stats.json", "w"), indent=4)

time_tag = datetime.datetime.now().strftime("%Y-%m-%d_%H")
output_key = f"deepdive_analysis_kmeans/cny_8_month_2025-10-20_17-41-50/output/cluster_stats_{year}_{time_tag}.json"
upload_file_to_s3(f"{OUTPUT_DIR}/cluster_stats.json", S3_BUCKET, output_key)
