"""
prepare data statistics of wucaishen cluster data to support GAI simulation. This statistics defines the start state of
the simulation model.
The cluster data is generated by sagemaker jobs cluster_analysis_*.py

bet statistics for basepoint, all account (bet amount) values with its frequency.
"""

import datetime
import json
import os
from collections import Counter

import numpy as np
from sklearn.preprocessing import StandardScaler

from bituslabs_ds.config import S3_BUCKET, setup_logging
from bituslabs_ds.s3_utils import read_files, upload_file_to_s3

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

setup_logging(f"{SCRIPT_DIR}.log/data_process_wucaishen_cluster_stats.log")

year = 2024
wucaishen_enriched_with_clusters = [
    "s3://bituslabs-team-ai/ds-data-kmeans/wucaishen_with_cluster_2024_0.csv",
    "s3://bituslabs-team-ai/ds-data-kmeans/wucaishen_with_cluster_2024_1.csv",
    "s3://bituslabs-team-ai/ds-data-kmeans/wucaishen_with_cluster_2024_2.csv",
]

year = 2025
wucaishen_enriched_with_clusters = [
    "s3://bituslabs-team-ai/ds-data-kmeans/2025_2025-06-18_16-43-44/wucaishen_with_cluster_2025_0.csv",
    "s3://bituslabs-team-ai/ds-data-kmeans/2025_2025-06-18_16-43-44/wucaishen_with_cluster_2025_1.csv",
    "s3://bituslabs-team-ai/ds-data-kmeans/2025_2025-06-18_16-43-44/wucaishen_with_cluster_2025_2.csv",
]

scaler = StandardScaler()
cluster_stats = {}
for cluster_index in range(3):
    data = read_files(
        [wucaishen_enriched_with_clusters[cluster_index]],
        local_cache_path=f"{SCRIPT_DIR}/output/wucaishen_enriched_with_clusters_{year}_{cluster_index}.csv",
        columns=["basepoint", "account"],
    )

    scaler.fit(data["basepoint"].to_frame())

    stats = {
        "basepoint_mean": data["basepoint"].mean(),
        "basepoint_scaler_mean": scaler.mean_[0],
        "basepoint_median": data["basepoint"].median(),
        "basepoint_std": data["basepoint"].std(),
        "basepoint_scaler_std": np.sqrt(scaler.var_[0]),
        "account_counter": Counter(data["account"]),
    }
    cluster_stats[f"cluster_{cluster_index}"] = stats

json.dump(cluster_stats, open(f"{SCRIPT_DIR}/output/cluster_stats.json", "w"), indent=4)

time_tag = datetime.datetime.now().strftime("%Y-%m-%d_%H")
output_key = f"ds-data-kmeans/wucaishen_cluster_stats_{year}_{time_tag}.json"
upload_file_to_s3(f"{SCRIPT_DIR}/output/cluster_stats.json", S3_BUCKET, output_key)
