"""
Plot a debugging output of a sagemaker job:
"""

import boto3
import IPython
import matplotlib.pyplot as plt
import sagemaker
from mpl_toolkits.axes_grid1 import host_subplot
from sagemaker.pytorch import PyTorch
from smdebug.core.modes import ModeKeys
from smdebug.profiler.analysis.notebook_utils.timeline_charts import TimelineCharts
from smdebug.profiler.analysis.notebook_utils.training_job import TrainingJob
from smdebug.trials import create_trial


def get_data(trial, tname, mode):
    tensor = trial.tensor(tname)
    steps = tensor.steps(mode=mode)
    vals = []
    for s in steps:
        vals.append(tensor.value(s, mode=mode))
    return steps, vals


def plot_tensor(trial, tensor_name):

    steps_train, vals_train = get_data(trial, tensor_name, mode=ModeKeys.TRAIN)
    print("loaded TRAIN data")
    steps_eval, vals_eval = get_data(trial, tensor_name, mode=ModeKeys.EVAL)
    print("loaded EVAL data")

    fig = plt.figure(figsize=(10, 7))
    host = host_subplot(111)

    par = host.twiny()

    host.set_xlabel("Steps (TRAIN)")
    par.set_xlabel("Steps (EVAL)")
    host.set_ylabel(tensor_name)

    (p1,) = host.plot(steps_train, vals_train, label=tensor_name)
    print("completed TRAIN plot")
    (p2,) = par.plot(steps_eval, vals_eval, label="val_" + tensor_name)
    print("completed EVAL plot")
    leg = plt.legend()

    host.xaxis.get_label().set_color(p1.get_color())
    leg.texts[0].set_color(p1.get_color())

    par.xaxis.get_label().set_color(p2.get_color())
    leg.texts[1].set_color(p2.get_color())

    plt.ylabel(tensor_name)

    plt.show()


def create_profiler():

    session = boto3.session.Session()
    region = session.region_name

    training_job_name = estimator.latest_training_job.name
    print(f"Training jobname: {training_job_name}")
    print(f"Region: {region}")

    tj = TrainingJob(training_job_name, region)
    tj.wait_for_sys_profiling_data_to_be_available()

    system_metrics_reader = tj.get_systems_metrics_reader()
    system_metrics_reader.refresh_event_file_list()

    view_timeline_charts = TimelineCharts(
        system_metrics_reader,
        framework_metrics_reader=None,
        select_dimensions=["CPU", "GPU"],
        select_events=["total"],
    )

    rule_output_path = estimator.output_path + estimator.latest_training_job.job_name + "/rule-output"
    print(f"You will find the profiler report in {rule_output_path}")

    # get the autogenerated folder name of profiler report
    profiler_report_name = [
        rule["RuleConfigurationName"]
        for rule in estimator.latest_training_job.rule_job_summary()
        if "Profiler" in rule["RuleConfigurationName"]
    ][0]

    IPython.display.HTML(filename=profiler_report_name + "/profiler-output/profiler-report.html")


if __name__ == "__main__":

    job_name = "pytorch-training-2025-08-27-00-47-32-919"
    sagemaker_session = sagemaker.Session()

    estimator = PyTorch.attach(training_job_name=job_name, sagemaker_session=sagemaker_session)

    client = estimator.sagemaker_session.sagemaker_client
    description = client.describe_training_job(TrainingJobName=estimator.latest_training_job.name)

    trial = create_trial(estimator.latest_job_debugger_artifacts_path())

    plot_tensor(trial, "nll_loss_output_0")

    create_profiler()
